/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbrand: typeof import('./src/components/layout/Appbrand.vue')['default']
    AudioProcess: typeof import('./src/components/views/AudioProcess/index.vue')['default']
    DropDown: typeof import('./src/components/common/DropDown.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    'IconEp-{{': typeof import('~icons/ep/{{')['default']
    IconEpPicture: typeof import('~icons/ep/picture')['default']
    ImageProcess: typeof import('./src/components/views/ImageProcess/index.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
  }
}
